<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AboutUs.aspx.cs" Inherits="AboutUs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <strong style="font-weight: bold;"><span style="font-family: Verdana, sans-serif; font-size: 12pt;">About DIS</span></strong><span style="font-size: 10pt; font-family: Verdana, sans-serif;"><strong style="font-weight: bold;">&nbsp;</strong></span>&nbsp;</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-size: 10pt; font-family: Verdana, sans-serif;">In 2000,&nbsp;Mr. Md. Sabur Khan&nbsp;initiated a program of an integrated network / pathway of academic institutions, dedicated to expanding access to education of an international standard of excellence. The academies, which educate young men and women from pre-primary to university.</span>&nbsp;&nbsp;</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-size: 10pt; font-family: Verdana, sans-serif;">Daffodil International School is sponsored by Daffodil Computers Ltd. strives to create a harmonious balance between academic demands, sporting, cultural activities and community life. The school is a part of Daffodil Group. Daffodil Group has a long tradition of leadership in ICT and educational development in Bangladesh. Daffodil Group operates Daffodil International University (DIU), Daffodil Institute of IT (DIIT), Daffodil International College (DIC), Bangladesh Skill Development Institute (BSDI) and Daffodil International School services more than 20,000 students in Bangladesh. Daffodil Group also developing new schools in Malaysia, Nepal, Dubai, Bahrain, and UK.</span>&nbsp;</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-size: 10pt; font-family: Verdana, sans-serif;">Mr. Md. Sabur Khan experiences include the behavioral and motivational aspects of different age groups. He traveled and surveyed educational systems around the globe. He is the member of many national &amp; international societies. He has more than 20 years experience to run the academic Institutions (School -DIS, College-DIC, Institute-DIIT, University-DIU) of Bangladesh and abroad.<br />
    </span>
</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <strong style="font-weight: bold;"><span style="font-family: Verdana, sans-serif;">Mission</span></strong></p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-size: 10pt; font-family: Verdana, sans-serif;">
    <br />
    </span>OUR MISSION</p>
<p style="margin: 0px 0px 9px; word-wrap: break-word; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    The mission of DIS is to help young minds grow and learn in a harmonious environment resulting in the all-round development of our children. Each student’s full potential is nurtured in a friendly, caring atmosphere, which fosters intellectual, social, emotional and physical growth.</p>
<p style="margin: 0px 0px 9px; word-wrap: break-word; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    OUR VISION</p>
<p style="margin: 0px 0px 9px; word-wrap: break-word; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    A dynamic learning community recognized as one of the leading schools in Bangladesh, offering an international curriculum in English but emphasizing equal proficiency in Bengali as a necessary prerequisite for a well-rounded education for students of Bangladesh.</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    &nbsp;</p>
<p align="justify" style="margin: 0px 0px 9px; word-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-family: Verdana, sans-serif;">Objectives<br />
    </span><span style="font-size: 10pt; font-family: Verdana, sans-serif;">The total programme at DIS addresses the whole child emphasizing the development of total personality. Our objectives are :</span>&nbsp;</p>
<ul style="padding: 0px; margin: 0px 0px 9px 25px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal;">
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To introduce the child to the joys of learning through companionship and recreational activities.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To stimulate and satisfy the child&#39;s curiosity about his environment and provide an opportunity to discover and explore with the hands-on material.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To channelize his energy through recreational activities.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To develop the child&#39;s ability to express his thoughts and feelings in a fluent language and in a confident manner.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To orient the child to develop self-confidence, self-dependability, honesty and social skills through group interaction.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To inculcate good habits, social manners and etiquettes among children.</span></li>
    <li style="line-height: 18px; word-wrap: break-word;"><span style="font-size: 10pt; font-family: Verdana, sans-serif;">To enlarge the mental horizons and broaden the outlook of the children.</span></li>
</ul>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<div class="moduletable" style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    <div style="border: 0px !important;">
        <div id="djslider-loader116" class="djslider-loader djslider-loader-default" style="margin: 0px auto; position: relative; background: none; max-width: 100%; overflow: hidden;" tabindex="0">
            <div id="djslider116" class="djslider djslider-default img-vcenter" style="margin: 0px auto; position: relative; transition: opacity 400ms ease; opacity: 1; height: 228.649px; width: 940px;">
                <div id="slider-container116" class="slider-container" style="position: absolute; overflow: hidden; left: 0px; top: 0px; height: 228.641px; width: 940px;">
                    <ul id="slider116" class="djslider-in" style="padding: 0px !important; margin: 0px !important; position: relative; border: 0px !important; left: 0px; width: 1588.33px; transition: left 1000ms ease-out;">
                        <li style="line-height: 18px; text-align: center; float: left; position: relative; background: none; overflow: hidden; box-sizing: border-box; list-style: none outside !important; padding: 0px !important; border: 0px !important; height: 228.649px; width: 306.667px; margin: 0px 10px 0px 0px !important;"><a class="image-link" data-title="" href="https://dis.edu.bd/images/sampledata/fruitshop/7th-Bangla-Olympiad.jpg" style="color: rgb(13, 12, 12); text-decoration: none;" tabindex="0" target="_self">
                            <img alt="7th-Bangla-Olympiad.jpg" class="dj-image" src="https://dis.edu.bd/images/sampledata/fruitshop/7th-Bangla-Olympiad.jpg" style="border-style: none; border-color: inherit; border-width: 0px; max-width: 100%; height: auto; vertical-align: middle; margin: 0px; position: relative; top: 1px; transform: translateY(-50%); width: 306.656px; left: -1px;" /></a></li>
                        <li style="line-height: 18px; text-align: center; float: left; position: relative; background: none; overflow: hidden; box-sizing: border-box; list-style: none outside !important; padding: 0px !important; border: 0px !important; height: 228.649px; width: 306.667px; margin: 0px 10px 0px 0px !important;"><a class="image-link" data-title="" href="https://dis.edu.bd/images/sampledata/fruitshop/1930889_2092335984116010_1586883555794116874_n-1.jpg" style="color: rgb(13, 12, 12); text-decoration: none;" tabindex="0" target="_self">
                            <img alt="1930889_2092335984116010_1586883555794116874_n-1.jpg" class="dj-image" src="https://dis.edu.bd/images/sampledata/fruitshop/1930889_2092335984116010_1586883555794116874_n-1.jpg" style="max-width: 100%; height: auto; vertical-align: middle; border: 0px !important; margin: 0px !important; position: relative; top: 0px; transform: translateY(-50%); width: 306.656px;" /></a></li>
                        <li style="line-height: 18px; text-align: center; float: left; position: relative; background: none; overflow: hidden; box-sizing: border-box; list-style: none outside !important; padding: 0px !important; border: 0px !important; height: 228.649px; width: 306.667px; margin: 0px 10px 0px 0px !important;"><a class="image-link" data-title="" href="https://dis.edu.bd/images/sampledata/fruitshop/28471625_2092398140776461_2660211780652812954_n.jpg" style="color: rgb(13, 12, 12); text-decoration: none;" tabindex="0" target="_self">
                            <img alt="28471625_2092398140776461_2660211780652812954_n.jpg" class="dj-image" src="https://dis.edu.bd/images/sampledata/fruitshop/28471625_2092398140776461_2660211780652812954_n.jpg" style="border-style: none; border-color: inherit; border-width: 0px; max-width: 100%; height: auto; vertical-align: middle; margin: 0px; position: relative; top: 4px; transform: translateY(-50%); width: 306.656px; left: -9px;" /></a></li>
                        <li style="line-height: 18px; text-align: center; float: left; position: relative; background: none; overflow: hidden; box-sizing: border-box; list-style: none outside !important; padding: 0px !important; border: 0px !important; height: 228.649px; width: 306.667px; margin: 0px 10px 0px 0px !important;"><a class="image-link" data-title="" href="https://dis.edu.bd/images/sampledata/fruitshop/29388804_558843817828374_8931139788036643562_n.jpg" style="color: rgb(13, 12, 12); text-decoration: none;" tabindex="-1" target="_self">
                            <img alt="29388804_558843817828374_8931139788036643562_n.jpg" class="dj-image" src="https://dis.edu.bd/images/sampledata/fruitshop/29388804_558843817828374_8931139788036643562_n.jpg" style="border-style: none; border-color: inherit; border-width: 0px; max-width: 100%; height: auto; vertical-align: middle; margin: 0px; position: relative; top: 0px; transform: translateY(-50%); width: 306.656px; left: -6px;" /></a></li>
                        <li style="line-height: 18px; text-align: center; float: left; position: relative; background: none; overflow: hidden; box-sizing: border-box; list-style: none outside !important; padding: 0px !important; border: 0px !important; height: 228.649px; width: 306.667px; margin: 0px 10px 0px 0px !important;"><a class="image-link" data-title="" href="https://dis.edu.bd/images/sampledata/fruitshop/Pre-school--Annual-Sports-Day-2018.jpg" style="color: rgb(13, 12, 12); text-decoration: none;" tabindex="-1" target="_self">
                            <img alt="Pre-school--Annual-Sports-Day-2018.jpg" class="dj-image" src="https://dis.edu.bd/images/sampledata/fruitshop/Pre-school--Annual-Sports-Day-2018.jpg" style="max-width: 100%; height: auto; vertical-align: middle; border: 0px !important; margin: 0px !important; position: relative; top: 0px; transform: translateY(-50%); width: 306.656px;" /></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="djslider-end" style="clear: both;" tabindex="0">
    </div>
</div>
<div class="row-fluid" style="width: 940px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
</div>
<div class="row-fluid" style="width: 940px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    <main id="content" role="main" class="span12" style="float: left; min-height: 28px; margin-left: 0px; width: 940px; display: block; box-sizing: border-box;">
    <div id="system-message-container">
        <div itemprop="articleBody">
            <p style="margin: 0px 0px 9px;">
                <strong style="font-weight: bold;">OUR MISSION</strong></p>
            <p style="margin: 0px 0px 9px;">
                The mission of DIS is to help young minds grow and learn in a harmonious environment resulting in the all-round development of our children. Each student’s full potential is nurtured in a friendly, caring atmosphere, which fosters intellectual, social, emotional and physical growth.</p>
            <p style="margin: 0px 0px 9px;">
                <strong style="font-weight: bold;">OUR VISION</strong></p>
            <p style="margin: 0px 0px 9px;">
                A dynamic learning community recognized as one of the leading schools in Bangladesh, offering an international curriculum in English but emphasizing equal proficiency in Bengali as a necessary prerequisite for a well-rounded education for students of Bangladesh.</p>
        </div>
    </div>
    </main>
</div>
<p>
    &nbsp;</p>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>

