<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="HomePage.aspx.cs" Inherits="HomePage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
        &nbsp;</p>
<h3 class="page-header" style="margin: 0px 0px 5px; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: bold; line-height: 20px; color: rgb(255, 255, 255); text-rendering: optimizeLegibility; font-size: 18px; padding: 6px; border-bottom: 1px solid rgb(238, 238, 238); background: rgb(12, 77, 162); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Administration</h3>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <p>
&nbsp;<strong>Chairman&#39;s Massage </strong>
</p>
<p>
    <img src="Images/saburkhan.jpg" style="width: 165px; height: 194px" /></p>
<p style="margin: 0in 0in 7.55pt; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; background: white;">
    <span style="font-family: Arial, sans-serif; color: black;">Welcome to our world, where technology interfaces with the human sensibility to form an alliance for change, dedicated exclusively to enrich human lives.&nbsp; Welcome to Daffodil, Bangladesh, an organization that takes pride in shaping aspirations and dreams and bringing them to fruition. Daffodil Group is a service-oriented organization committed to of disseminating the knowledge and skills required for the demanding economy of the twenty-first century.</span></p>
<p style="margin: 0in 0in 7.55pt; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; background: white;">
    <span style="font-family: Arial, sans-serif; color: black;">The spectacular growth of Daffodil Bangladesh can be attributed to its uncompromising commitment to quality and its dedication to the ideals of education through empowerment of its academic community. Daffodil Group is firmly committed to the evolution of education, through effective curriculum design, quality instructions, and excellent research with the co-existance of faculty and students. Education should aim at the liberation of one&#39;s inner powers of the mind and the body. To achieve this end, it has to be integral; it should encompass the physical, mental, emotional, psychic and spiritual planes. At the same time, education should take into account the giant strides mankind has taken in Science &amp; Technology and should, therefore, receive have a global orientation.</span></p>
<p style="margin: 0in 0in 7.55pt; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; background: white;">
    <span style="font-family: Arial, sans-serif; color: black;">Daffodil International School (DIS) has measured up to the expectations of the people of Bangladesh and become a role model in the field of quality education. While I am grateful to our patrons for reposing their continued faith and confidence in our efforts to raise a state-of-the-art institution committed to providing truly world class education in Bangladesh, parents who entrust their wards in our hands should know that Daffodil International School is not just an academic institution but a cult way of life - a covenant that becomes a hallmark in the scholar&#39;s life and in whose portals the destiny of the nation is shaped.Our vision is to integrate and synthesize physical education, vital and emotional education, mental and rational education, aesthetic, ethical and spiritual education. many different manifestations of education: Physical, emotional, mental, aesthetic, ethical and spiritual Our mission is to develop in our 
    students not only academic brilliance, competence a well-developed and integrated character but also such a refinement in their personality that they aspire to feel and sense their Higher Self or Soul within, raise themselves with the help of this presence and learn to live in by its guidance.</span></p>
<p style="margin: 0in 0in 7.55pt; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; background: white;">
    <span style="font-family: Arial, sans-serif; color: black;">We invite you to be a part of us and share the learning experience of Daffodil International School.</span></p>
<p style="margin: 0px 0px 9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    &nbsp;</p>
<p style="margin: 0px 0px 9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    &nbsp;</p>
<p style="margin: 0px 0px 9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-family: arial, helvetica, sans-serif;">Dr.&nbsp;Md. Sabur Khan</span></p>
<p style="margin: 0px 0px 9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-family: arial, helvetica, sans-serif;"><span style="font-size: 8pt;">Chairman, Governing Body</span></span></p>
<p style="margin: 0px 0px 9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; line-height: normal; text-align: justify;">
    <span style="font-family: arial, helvetica, sans-serif;"><span style="font-size: 8pt;">Daffodil International School (DIS)</span></span></p>
<h1 style="margin: 12px 0px; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: bold; line-height: 28px; color: rgb(51, 51, 51); text-rendering: optimizeLegibility; font-size: 26px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: bold;">Message from Principal</strong></h1>
<p style="margin: 12px 0px; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: bold; line-height: 28px; color: rgb(51, 51, 51); text-rendering: optimizeLegibility; font-size: 26px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <img src="Images/Advisor_Sir.png" style="width: 178px; height: 235px" /></p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    I have a dream-</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <em style="font-style: italic;">“Walking into a school with hundreds of enthusiastic learners smiling and greeting, ethically grounded and emotionally invested in the art of learning.”</em><span>&nbsp;</span>- It’s a unique reality that makes my dream successful and ever practical in Daffodil International School (DIS). I have discovered here an exceptional teaching and learning process which is managed by a group of highly qualified and efficient teachers from well-established educational backgrounds.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Indeed, DIS, seeks to personalize the learning experience for every student. The teachers, who are supported by a visionary board of management, provide quality pastoral care to ensure that the students are supported to achieve success at all levels of study. The moral and ethical bond between teachers, students and guardians enriches the school environment.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    For years, we have subscribed to a vision where we nurture interest in these youngsters’ minds. We have been entrusted with the greatest asset that one can have, children, and so we promise nothing less than absolute sincerity in molding them for a better and brighter tomorrow.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    We are committed to ensuring that every student receives the skills, knowledge and experience that will allow her or him to take the next step in their lives with confidence, when they leave Daffodil International School (DIS). We believe that we give our students the necessary tools to have a choice about their future.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Therefore, I welcome you to<span>&nbsp;</span><strong style="font-weight: bold;">DAFFODIL INTERNATIONAL SCHOOL (DIS),</strong><span>&nbsp;</span>which helps your children grow and learn in a harmonious environment, resulting in the all-round development of their bodies, minds and souls.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Please visit our website; www.dis.edu.bd to get more information about DIS.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    I wish you and your children the best.</p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <strong style="font-weight: bold;">Dr Md Mahmudul Hassan</strong></p>
<p style="margin: 0px 0px 9px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Principal, Dhaka</p>
<p style="margin: 12px 0px; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: bold; line-height: 28px; color: rgb(51, 51, 51); text-rendering: optimizeLegibility; font-size: 26px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    &nbsp;</p>
<p>
    &nbsp;</p>
<p>
    <img src="Images/siskin1.jpg" style="width: 140px; height: 150px" /></p>
<p>
    <span style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">What I will remember about Daffodil International School is the tremendous spirit of students, faculty, and staff. People are constantly coming up with new ideas, programs, and activities. There is a keen interest in what is happening beyond the borders of Bangladesh, for which DIS truly deserves the “International” in its name. DIS provides a supportive atmosphere for learning and teaching.</span><br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <strong style="box-sizing: border-box; font-weight: bold; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Professor Claire Bradin Siskin<span>&nbsp;</span></strong><br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <img alt="C-Siskin" src="https://daffodilvarsity.edu.bd/photos/visitor/C-Siskin.jpg" style="box-sizing: border-box; border: 0px; vertical-align: middle; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" /></p>
<p>
    <img src="Images/suzuki.jpg" style="width: 152px; height: 150px" /></p>
<p>
    <span style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">I am deeply impressed by the serious look of the students during the lecture, and the politeness that everyone stands up when I was introduced at the class at DIS. Role of DIS is praiseworthy for promoting the study of power generation in the country for the future. Bangladeshi children with a lovely smile, as long as they are exposed to heart aching environment, I always face towards Bangladesh through Daffodil.</span><br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <strong style="box-sizing: border-box; font-weight: bold; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Takayoshi Suzuki</strong><br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
    <img alt="suzuki-" src="https://daffodilvarsity.edu.bd/photos/visitor/suzuki-.png" style="box-sizing: border-box; border: 0px; vertical-align: middle; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" /></p>
</asp:Content>

